BAH-4137 | Add Resend OTP for Abha creation and Abha verification.
Bahmni-Covid19/ndhm-react pull request #94
Opened 2024-12-09 12:24 UTC by arshiyaTW2021

This PR implements **resend OTP functionality** at the following scenarios :

1. Aadhaar OTP for ABHA Creation

2. Mobile OTP for ABHA Communication Mobile verification

3. ABHA Verification by ABHA Number, ABHA Address and Mobile Number

The resend OTP functionality should be enabled after 60 seconds with a maximum attempt of 2 times.

2024-12-11 11:21 UTC, rahu1ramesh commented on src/components/Common/ResendOtp.jsx
> +        if (attemptsLeft > 0) {
```
if (resendOtpDisabled || attemptsLeft <= 0) return;
```
@arshiya2125 an early exit would be cleaner is what I feel

2024-12-11 11:39 UTC, rahu1ramesh requested changes

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/Common/ResendOtp.jsx
> +        if (timeLeft > 0) {
```
        if (timeLeft <= 0) {
            setResendOtpDisabled(false);
            return;
        }

        const interval = setInterval(() => {
            setTimeLeft((prev) => prev - 1);
        }, 1000);

        return () => clearInterval(interval);
```

Using `setTimeLeft((prev) => prev - 1)` ensures `useEffect` always works with the latest state.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/creation/VerifyMobile.jsx
> +            setshowResendOtp(true);
Please do fix the indentation if possible.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/creation/VerifyMobile.jsx
> +        async function onResendOtp() {
I feel adding a try-catch-finally block would improve the code, catching unexpected errors, ensuring the user gets relevant feedback.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +	const handleOtpResend = async () => {
I feel adding a `try-catch-finally` block would improve the code, catching unexpected errors, ensuring the user gets relevant feedback.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +		if(aadhaarOtpResponse){
Adding an early exit here with a`setError(("Failed to receive a response. Please try again.")` would help the user get immediate feedback if `generateAadhaarOtp` fails.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +		var aadhaarOtpResponse = await generateAadhaarOtp(props.aadhaar);
Destructuring { aadhaar, mobile } at the parameter level makes the code cleaner and reduces repetitive props. usage, just a suggestion.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/otp-verification/otpVerification.jsx
> +        if(isVerifyByAbhaAddress){
```
const response = isVerifyByAbhaAddress
            ? await abhaAddressRequestOtp(props.id, props.selectedAuthMode)
            : await abhaNumberRequestOtp(props.id, props.selectedAuthMode);
```
Would be cleaner.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/otp-verification/otpVerification.jsx
> +        setErrorMessage("");
I feel adding a `try-catch-finally` block would improve the code, catching unexpected errors, ensuring the user gets relevant feedback.

2024-12-11 11:39 UTC, rahu1ramesh commented on src/components/verifyHealthId/verifyHealthIdThroughMobileNumber.jsx
> +    async function onResendOtp() {
I feel adding a `try-catch-finally` block would improve the code, catching unexpected errors, ensuring the user gets relevant feedback.

2024-12-11 12:17 UTC, mohan-13 commented on src/components/creation/VerifyMobile.jsx
> +        async function onResendOtp() {
For all the APIs, try catch and error parsing is handled at the API service file `hipApiService.js`

2024-12-11 12:17 UTC, mohan-13 commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +	const handleOtpResend = async () => {
For all the APIs, try catch and error parsing is handled at the API service file `hipApiService.js`

2024-12-11 12:18 UTC, mohan-13 commented on src/components/otp-verification/otpVerification.jsx
> +        setErrorMessage("");
For all the APIs, try catch and error parsing is handled at the API service file `hipApiService.js`

2024-12-11 12:18 UTC, mohan-13 commented on src/components/verifyHealthId/verifyHealthIdThroughMobileNumber.jsx
> +    async function onResendOtp() {
For all the APIs, try catch and error parsing is handled at the API service file `hipApiService.js`

2024-12-11 12:29 UTC, mohan-13 commented on src/components/Common/ResendOtp.jsx
> +        if (attemptsLeft > 0) {
@rahu1ramesh I feel that this condition would make it more readable that the click performs some operation only when you have some attempts left. Also early returns would be better if you have multiple conditions. In this case there is just a conditional check for attemptsLeft

2024-12-11 12:30 UTC, mohan-13 commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +		if(aadhaarOtpResponse){
All the error handling is done in a global error parser, so that the messages are consistent and messages are captured from different response formats.

2024-12-12 05:06 UTC, arshiyaTW2021 commented on src/components/creation/VerifyOTPAndCreateABHA.jsx
> +		var aadhaarOtpResponse = await generateAadhaarOtp(props.aadhaar);
We can take this up when we do the refactoring. As of now, we are following this pattern of not destructuring and would want to be consistent with it.

2024-12-12 05:07 UTC, arshiyaTW2021 commented on src/components/Common/ResendOtp.jsx
> +        if (timeLeft > 0) {
Good suggestion. Done.

2024-12-12 05:09 UTC, arshiyaTW2021 commented on src/components/otp-verification/otpVerification.jsx
> +        if(isVerifyByAbhaAddress){
done

2024-12-12 11:27 UTC, rahu1ramesh approved these changes

2024-12-12 13:28 UTC, merged